- action:
  - data:
      brightness: 255
      color_name: red
      entity_id: light.ledstrip
      flash: short
    service: light.turn_on
  alias: Alarm pohybu blikaj
  condition: []
  id: '1524939817686'
  trigger:
  - entity_id: binary_sensor.pir
    from: 'off'
    platform: state
    to: 'on'
